### ISSUE TITLE
Problems with non ascii commander names

### ISSUE THREAD

**Issue by bgol** [EDSM-NET/EDDN#94]
I think this line:
https://github.com/EDSM-NET/EDDN/blob/52a7061d8ff29c779b8d2313f2156462b3bc899d/src/eddn/Relay.py#L65
causes troubles with non ascii commander names.
This should fix it:
```python
return hashlib.sha1("{}-{}".format(self.uploader_nonce, uploader.encode('utf8'))).hexdigest()
```

**Comment by klightspeed** [comment]
Wouldn't it be the output of format that should be encoded in utf-8 in python 3.x?
```python
return hashlib.sha1("{}-{}".format(self.uploader_nonce, uploader).encode('utf8')).hexdigest()

```

**Comment by DarkWanderer** [comment]
No, because:

* sha1 output does not change whether input is ASCII or not, and with ASCII this works
* you can't 'encode' sha-1 output in utf-8 at all, as it's pseudorandom bytes

**Comment by bgol** [comment]
Yes, but it's python2, so it needs to be the uploader itself.

**Comment by klightspeed** [comment]
OK - it looks like EDDN does use Python 2.7, as the current code would require encoding the output of `format()` in python 3.x regardless of whether or not it has any non-ascii characters.

```
$ python2 -c 'from __future__ import print_function; import hashlib; import uuid; print(hashlib.sha1("{}-{}".format(uuid.uuid4(), u"Gr\xfcne H\xf6lle")).hexdigest())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 2: ordinal not in range(128)

$ python2 -c 'from __future__ import print_function; import hashlib; import uuid; print(hashlib.sha1("{}-{}".format(uuid.uuid4(), u"Gr\xfcne H\xf6lle".encode("utf-8"))).hexdigest())'
f549ae9648a29c44bec43019aa8b4a4dfb6a09a8

$ python3 -c 'from __future__ import print_function; import hashlib; import uuid; print(hashlib.sha1("{}-{}".format(uuid.uuid4(), u"Gr\xfcne H\xf6lle".encode("utf-8"))).hexdigest())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: Unicode-objects must be encoded before hashing

$ python3 -c 'from __future__ import print_function; import hashlib; import uuid; print(hashlib.sha1("{}-{}".format(uuid.uuid4(), u"Gr\xfcne H\xf6lle").encode("utf-8")).hexdigest())'
a52030f97216da57604a221361e69f81a9e79b66

$ python3 -c 'from __future__ import print_function; import hashlib; import uuid; print(hashlib.sha1("{}-{}".format(uuid.uuid4(), "Hello")).hexdigest())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by bgol** [comment]
fixed with commit https://github.com/EDSM-NET/EDDN/commit/9484f4646a6fcedac7bec79e659926fe95f6bec0
